import pytest

from env_helpers import make_env_settings
from todos_app.core.config.export import format_dotenv_value, render_dotenv


pytestmark = pytest.mark.unit


@pytest.mark.parametrize(
	("value", "expected"),
	[
		("8000", "8000"),
		(
			"postgresql+asyncpg://todos:pass@127.0.0.1:5432/todos",
			"postgresql+asyncpg://todos:pass@127.0.0.1:5432/todos",
		),
		("hello world", '"hello world"'),
		('say "hi"', '"say \\"hi\\""'),
		("foo$bar", '"foo\\$bar"'),
		("back\\slash", '"back\\\\slash"'),
		("has#hash", '"has#hash"'),
		("", '""'),
	],
)
def test_format_dotenv_value_quotes_when_needed(value: str, expected: str) -> None:
	assert format_dotenv_value(value) == expected


def test_render_dotenv_includes_header_profile_and_flattened_pairs() -> None:
	settings = make_env_settings(jwt_secret_key='secret-with-$pecial "chars" padding-32+')
	output = render_dotenv(settings, env_profile="test")

	assert output.startswith("# Generated by todos_app.core.config.export")
	assert "ENV_PROFILE=test\n" in output
	assert 'JWT_SECRET_KEY="secret-with-\\$pecial \\"chars\\" padding-32+"' in output
	assert "API_PORT=8000\n" in output
	assert output.endswith("\n")
