import argparse
import os
import shlex
import sys

from env_config.loader import get_profile_settings
from env_config.names import iter_env_pairs


def _shell_exports() -> str:
	settings = get_profile_settings()
	lines: list[str] = []
	if profile := os.environ.get("ENV_PROFILE"):
		lines.append(f"export ENV_PROFILE={shlex.quote(profile)}")
	for env_name, value in iter_env_pairs(settings):
		lines.append(f"export {env_name}={shlex.quote(value)}")
	return "\n".join(lines)


def _dotenv_lines() -> str:
	settings = get_profile_settings()
	lines: list[str] = ["# Generated by env_config.export — do not edit; update the env profile instead."]
	if profile := os.environ.get("ENV_PROFILE"):
		lines.append(f"ENV_PROFILE={profile}")
	for env_name, value in iter_env_pairs(settings):
		lines.append(f"{env_name}={value}")
	return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
	parser = argparse.ArgumentParser(description="Export env profile values for shell scripts and Compose.")
	group = parser.add_mutually_exclusive_group(required=True)
	group.add_argument("--shell", action="store_true", help="Print bash export statements")
	group.add_argument("--dotenv", action="store_true", help="Print KEY=value lines for Compose env_file")
	args = parser.parse_args(argv)

	if args.shell:
		sys.stdout.write(_shell_exports())
	elif args.dotenv:
		sys.stdout.write(_dotenv_lines())
	return 0


if __name__ == "__main__":
	raise SystemExit(main())
