"""add token_version and case_insensitive_username

Revision ID: 2422881b19ef
Revises: 1fd4467961ec
Create Date: 2026-06-13 13:30:45.677004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2422881b19ef'
down_revision: Union[str, Sequence[str], None] = '1fd4467961ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token_version', sa.Integer(), server_default='0', nullable=False))
    op.create_index('ix_users_username_lower', 'users', [sa.literal_column('lower(username)')], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_username_lower', table_name='users')
    op.drop_column('users', 'token_version')
    # ### end Alembic commands ###
