EMAIL_MAX_LENGTH = 254
USERNAME_MAX_LENGTH = 50
FIRST_NAME_MAX_LENGTH = 100
LAST_NAME_MAX_LENGTH = 100
HASHED_PASSWORD_MAX_LENGTH = 255
ROLE_MAX_LENGTH = 50

PASSWORD_MIN_LENGTH = 8
PASSWORD_MAX_LENGTH = 128
