from typing import Protocol
from uuid import UUID

from todos_app.domain.users.entity import User


class UserRepository(Protocol):
	async def add(self, user: User) -> User: ...

	async def update(self, user: User) -> User | None: ...

	async def get_by_id(self, user_id: UUID) -> User | None: ...

	async def get_by_username(self, username: str) -> User | None: ...

	async def delete(self, user_id: UUID) -> bool: ...

	async def count_active_admins(self) -> int: ...
