# Shared local port defaults. Source before .env so ${POSTGRES_PORT} / ${VALKEY_PORT} expand in URLs.

API_PORT="${API_PORT:-8000}"
POSTGRES_PORT="${POSTGRES_PORT:-5432}"
VALKEY_PORT="${VALKEY_PORT:-6379}"
COMPOSE_APP_BIND="${COMPOSE_APP_BIND:-127.0.0.1}"
COMPOSE_INFRA_BIND="${COMPOSE_INFRA_BIND:-127.0.0.1}"
