import os
import sys

from todos_app.core.config.flatten import iter_env_pairs
from todos_app.core.config.loader import get_profile_settings
from todos_app.core.config.schema import EnvSettings


def format_dotenv_value(value: str) -> str:
	"""Return dotenv value token, double-quoted when needed for bash source and Compose."""
	if not _needs_dotenv_quoting(value):
		return value
	escaped = value.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$")
	return f'"{escaped}"'


def _needs_dotenv_quoting(value: str) -> bool:
	if value == "":
		return True
	return any(ch in value for ch in ' \t\n\r"$\\#')


def render_dotenv(
	settings: EnvSettings | None = None,
	*,
	env_profile: str | None = None,
) -> str:
	resolved_settings = settings if settings is not None else get_profile_settings()
	if env_profile is None:
		env_profile = os.environ.get("ENV_PROFILE")
	lines: list[str] = [
		"# Generated by todos_app.core.config.export — do not edit; update config TOML instead.",
	]
	if env_profile:
		lines.append(f"ENV_PROFILE={format_dotenv_value(env_profile)}")
	for env_name, value in iter_env_pairs(resolved_settings):
		lines.append(f"{env_name}={format_dotenv_value(value)}")
	return "\n".join(lines) + "\n"


def main() -> int:
	sys.stdout.write(render_dotenv())
	return 0


if __name__ == "__main__":
	raise SystemExit(main())
